---
logging:
  level: INFO
  loggers:
    org.example: DEBUG

databaseUrl: jdbc:mysql://db:3306/todo_schema?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
databaseUser: root
databasePassword: 1234
