
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - todo-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_schema
    ports:
      - "3307:3306"
    networks:
      - todo-network
    volumes:
     - mysql_data:/var/lib/mysql
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql



networks:
  todo-network:
    driver: bridge
volumes:
  mysql_data:
